<?php

/**
 * implementation of hook_views_default_views().
 */
function species_pages_tweaks_views_default_views_alter(&$views){

  $view = NULL;

  if (isset($views['species_specimen'])) {
    $view = $views['species_specimen'];
  }else{
    trigger_error('view not found');
  }

  $handler =& $view->display['default']->handler;
  // Add the user name field to the view.
  $handler->display->display_options['fields'] = NULL;

  /* Relationship: Specimen/Location */
  $handler->display->display_options['relationships']['field_location_nid']['id'] = 'field_location_nid';
  $handler->display->display_options['relationships']['field_location_nid']['table'] = 'field_data_field_location';
  $handler->display->display_options['relationships']['field_location_nid']['field'] = 'field_location_nid';
  $handler->display->display_options['relationships']['field_location_nid']['ui_name'] = 'Specimen/Location';
  $handler->display->display_options['relationships']['field_location_nid']['required'] = 0;
  $handler->display->display_options['relationships']['field_location_nid']['delta'] = '-1';

  /* Field: Field: Taxonomic name */
  $handler->display->display_options['fields']['field_taxonomic_name']['id'] = 'field_taxonomic_name';
  $handler->display->display_options['fields']['field_taxonomic_name']['table'] = 'field_data_field_taxonomic_name';
  $handler->display->display_options['fields']['field_taxonomic_name']['field'] = 'field_taxonomic_name';
  $handler->display->display_options['fields']['field_taxonomic_name']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_taxonomic_name']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_taxonomic_name']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['element_type'] = '0';
  $handler->display->display_options['fields']['field_taxonomic_name']['element_label_type'] = 'strong';
  $handler->display->display_options['fields']['field_taxonomic_name']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_taxonomic_name']['element_default_classes'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['field_taxonomic_name']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_taxonomic_name'] = array(
    'width' => 120,
    'sortable' => 1,
    'tab' => 'Specimen list',
    'filter' => 'textFilter'
  );

  /* Field: Content: Institution code */
  $handler->display->display_options['fields']['field_institution_code']['id'] = 'field_institution_code';
  $handler->display->display_options['fields']['field_institution_code']['table'] = 'field_data_field_institution_code';
  $handler->display->display_options['fields']['field_institution_code']['field'] = 'field_institution_code';
  $handler->display->display_options['fields']['field_institution_code']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_institution_code']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_institution_code']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['element_type'] = '0';
  $handler->display->display_options['fields']['field_institution_code']['element_label_type'] = 'strong';
  $handler->display->display_options['fields']['field_institution_code']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_institution_code']['element_default_classes'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['field_institution_code']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_institution_code'] = array(
    'width' => 120,
    'sortable' => 1,
    'tab' => 'Specimen list',
    'filter' => 'textFilter'
  );
  /* Field: Content: Collection code */
  $handler->display->display_options['fields']['field_collection_code']['id'] = 'field_collection_code';
  $handler->display->display_options['fields']['field_collection_code']['table'] = 'field_data_field_collection_code';
  $handler->display->display_options['fields']['field_collection_code']['field'] = 'field_collection_code';
  $handler->display->display_options['fields']['field_collection_code']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_collection_code']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_collection_code']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['element_type'] = '0';
  $handler->display->display_options['fields']['field_collection_code']['element_label_type'] = 'strong';
  $handler->display->display_options['fields']['field_collection_code']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_collection_code']['element_default_classes'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['field_collection_code']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_collection_code'] = array(
    'width' => 120,
    'sortable' => 1,
    'tab' => 'Specimen list',
    'filter' => 'textFilter'
  );
  /* Field: Content: Catalogue number */
  $handler->display->display_options['fields']['field_catalogue_number']['id'] = 'field_catalogue_number';
  $handler->display->display_options['fields']['field_catalogue_number']['table'] = 'field_data_field_catalogue_number';
  $handler->display->display_options['fields']['field_catalogue_number']['field'] = 'field_catalogue_number';
  $handler->display->display_options['fields']['field_catalogue_number']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_catalogue_number']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_catalogue_number']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['element_type'] = '0';
  $handler->display->display_options['fields']['field_catalogue_number']['element_label_type'] = 'strong';
  $handler->display->display_options['fields']['field_catalogue_number']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_catalogue_number']['element_default_classes'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['field_catalogue_number']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_catalogue_number'] = array(
    'width' => 120,
    'sortable' => 1,
    'tab' => 'Specimen list',
    'filter' => 'textFilter'
  );
  /* Field: Content: Basis of record */
  $handler->display->display_options['fields']['field_basis_of_record']['id'] = 'field_basis_of_record';
  $handler->display->display_options['fields']['field_basis_of_record']['table'] = 'field_data_field_basis_of_record';
  $handler->display->display_options['fields']['field_basis_of_record']['field'] = 'field_basis_of_record';
  $handler->display->display_options['fields']['field_basis_of_record']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_basis_of_record']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_basis_of_record']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['element_type'] = '0';
  $handler->display->display_options['fields']['field_basis_of_record']['element_label_type'] = 'strong';
  $handler->display->display_options['fields']['field_basis_of_record']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_basis_of_record']['element_default_classes'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['field_basis_of_record']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_basis_of_record'] = array(
    'width' => 120,
    'sortable' => 1,
    'tab' => 'Specimen list',
    'filter' => 'textFilter'
  );
  /* Field: Content: Date collected */
  $handler->display->display_options['fields']['field_date_collected']['id'] = 'field_date_collected';
  $handler->display->display_options['fields']['field_date_collected']['table'] = 'field_data_field_date_collected';
  $handler->display->display_options['fields']['field_date_collected']['field'] = 'field_date_collected';
  $handler->display->display_options['fields']['field_date_collected']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_date_collected']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_date_collected']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['element_type'] = '0';
  $handler->display->display_options['fields']['field_date_collected']['element_label_type'] = 'strong';
  $handler->display->display_options['fields']['field_date_collected']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_date_collected']['element_default_classes'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['field_date_collected']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_date_collected'] = array(
    'width' => 120,
    'sortable' => 1,
    'tab' => 'Specimen list',
    'filter' => 'textFilter'
  );
  /* Field: Node: Link */
  $handler->display->display_options['fields']['view_node']['id'] = 'view_node';
  $handler->display->display_options['fields']['view_node']['table'] = 'views_entity_node';
  $handler->display->display_options['fields']['view_node']['field'] = 'view_node';
  $handler->display->display_options['fields']['view_node']['label'] = '';
  $handler->display->display_options['fields']['view_node']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['view_node']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['view_node']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['view_node']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['view_node']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['view_node']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['view_node']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['view_node']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['view_node']['alter']['more_link'] = 0;
  $handler->display->display_options['fields']['view_node']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['view_node']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['view_node']['alter']['html'] = 0;
  $handler->display->display_options['fields']['view_node']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['view_node']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['view_node']['hide_empty'] = 0;
  $handler->display->display_options['fields']['view_node']['empty_zero'] = 0;
  $handler->display->display_options['fields']['view_node']['hide_alter_empty'] = 1;
  $handler->display->display_options['style_options']['columns']['view_node'] = array(
    'width' => 120,
    'sortable' => 1,
    'tab' => 'Specimen list',
    'filter' => 'textFilter'
  );
  /* Field: Content: Map */
  $handler->display->display_options['fields']['field_map']['id'] = 'field_map';
  $handler->display->display_options['fields']['field_map']['table'] = 'field_data_field_map';
  $handler->display->display_options['fields']['field_map']['field'] = 'field_map';
  $handler->display->display_options['fields']['field_map']['relationship'] = 'field_location_nid';
  $handler->display->display_options['fields']['field_map']['label'] = 'Latitude';
  $handler->display->display_options['fields']['field_map']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_map']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_map']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_map']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_map']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['field_map']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['field_map']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_map']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_map']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_map']['alter']['more_link'] = 0;
  $handler->display->display_options['fields']['field_map']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_map']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_map']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_map']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_map']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_map']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_map']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_map']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['field_map']['click_sort_column'] = 'latitude';
  $handler->display->display_options['fields']['field_map']['type'] = 'gm3_latitude';
  $handler->display->display_options['fields']['field_map']['settings'] = array(
    'display_convex_hull' => FALSE,
  );
  $handler->display->display_options['fields']['field_map']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_map'] = array(
    'width' => 120,
    'sortable' => 1,
    'tab' => 'Specimen list',
    'filter' => 'textFilter'
  );
  /* Field: Content: Map */
  $handler->display->display_options['fields']['field_map_1']['id'] = 'field_map_1';
  $handler->display->display_options['fields']['field_map_1']['table'] = 'field_data_field_map';
  $handler->display->display_options['fields']['field_map_1']['field'] = 'field_map';
  $handler->display->display_options['fields']['field_map_1']['relationship'] = 'field_location_nid';
  $handler->display->display_options['fields']['field_map_1']['label'] = 'Longitude';
  $handler->display->display_options['fields']['field_map_1']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_map_1']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_map_1']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_map_1']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_map_1']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['field_map_1']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['field_map_1']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_map_1']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_map_1']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_map_1']['alter']['more_link'] = 0;
  $handler->display->display_options['fields']['field_map_1']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_map_1']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_map_1']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_map_1']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_map_1']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_map_1']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_map_1']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_map_1']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['field_map_1']['click_sort_column'] = 'latitude';
  $handler->display->display_options['fields']['field_map_1']['type'] = 'gm3_longitude';
  $handler->display->display_options['fields']['field_map_1']['settings'] = array(
    'display_convex_hull' => FALSE,
  );
  $handler->display->display_options['fields']['field_map_1']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_map_1'] = array(
    'width' => 120,
    'sortable' => 1,
    'tab' => 'Specimen list',
    'filter' => 'textFilter'
  );
}


