<?php

/**
 * implementation of hook_views_default_views().
 */
function species_pages_tweaks_views_default_views_alter(&$views){

  $view = NULL;

  if (isset($views['species_specimen'])) {
    $view = $views['species_specimen'];
  }else{
    trigger_error('view not found: species_specimen');
  }

  $handler =& $view->display['default']->handler;
  // Add the user name field to the view.
  $handler->display->display_options['fields'] = NULL;

  $handler->display->display_options['style_options']['forceFitColumns'] = 0;
  $handler->display->display_options['style_options']['select_columns'] = 0;

  /* Relationship: Specimen/Location */
  $handler->display->display_options['relationships']['field_location_nid']['id'] = 'field_location_nid';
  $handler->display->display_options['relationships']['field_location_nid']['table'] = 'field_data_field_location';
  $handler->display->display_options['relationships']['field_location_nid']['field'] = 'field_location_nid';
  $handler->display->display_options['relationships']['field_location_nid']['ui_name'] = 'Specimen/Location';
  $handler->display->display_options['relationships']['field_location_nid']['required'] = 0;
  $handler->display->display_options['relationships']['field_location_nid']['delta'] = '-1';

  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['title']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['title']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = 0;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = 0;
  $handler->display->display_options['fields']['title']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['title']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['title']['alter']['html'] = 0;
  $handler->display->display_options['fields']['title']['hide_empty'] = 0;
  $handler->display->display_options['fields']['title']['empty_zero'] = 0;
  $handler->display->display_options['fields']['title']['link_to_node'] = 1;

  /* Field: Field: Taxonomic name */
  $handler->display->display_options['fields']['field_taxonomic_name']['id'] = 'field_taxonomic_name';
  $handler->display->display_options['fields']['field_taxonomic_name']['table'] = 'field_data_field_taxonomic_name';
  $handler->display->display_options['fields']['field_taxonomic_name']['field'] = 'field_taxonomic_name';
  $handler->display->display_options['fields']['field_taxonomic_name']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_taxonomic_name']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_taxonomic_name']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['element_type'] = '0';
  $handler->display->display_options['fields']['field_taxonomic_name']['element_label_type'] = 'strong';
  $handler->display->display_options['fields']['field_taxonomic_name']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_taxonomic_name']['element_default_classes'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_taxonomic_name']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['field_taxonomic_name']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_taxonomic_name'] = array(
    'width' => 120,
    'sortable' => 1,
    'tab' => 'Brief',
    'filter' => 'textFilter'
  );

  /* Field: Content: Institution code */
  $handler->display->display_options['fields']['field_institution_code']['id'] = 'field_institution_code';
  $handler->display->display_options['fields']['field_institution_code']['table'] = 'field_data_field_institution_code';
  $handler->display->display_options['fields']['field_institution_code']['field'] = 'field_institution_code';
  $handler->display->display_options['fields']['field_institution_code']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_institution_code']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_institution_code']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['element_type'] = '0';
  $handler->display->display_options['fields']['field_institution_code']['element_label_type'] = 'strong';
  $handler->display->display_options['fields']['field_institution_code']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_institution_code']['element_default_classes'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_institution_code']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['field_institution_code']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_institution_code'] = array(
    'width' => 120,
    'sortable' => 1,
    'tab' => 'Brief',
    'filter' => 'textFilter'
  );
  /* Field: Content: Collection code */
  $handler->display->display_options['fields']['field_collection_code']['id'] = 'field_collection_code';
  $handler->display->display_options['fields']['field_collection_code']['table'] = 'field_data_field_collection_code';
  $handler->display->display_options['fields']['field_collection_code']['field'] = 'field_collection_code';
  $handler->display->display_options['fields']['field_collection_code']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_collection_code']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_collection_code']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['element_type'] = '0';
  $handler->display->display_options['fields']['field_collection_code']['element_label_type'] = 'strong';
  $handler->display->display_options['fields']['field_collection_code']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_collection_code']['element_default_classes'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_collection_code']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['field_collection_code']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_collection_code'] = array(
    'width' => 120,
    'sortable' => 1,
    'tab' => 'Brief',
    'filter' => 'textFilter'
  );
  /* Field: Content: Catalogue number */
  $handler->display->display_options['fields']['field_catalogue_number']['id'] = 'field_catalogue_number';
  $handler->display->display_options['fields']['field_catalogue_number']['table'] = 'field_data_field_catalogue_number';
  $handler->display->display_options['fields']['field_catalogue_number']['field'] = 'field_catalogue_number';
  $handler->display->display_options['fields']['field_catalogue_number']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_catalogue_number']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_catalogue_number']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['element_type'] = '0';
  $handler->display->display_options['fields']['field_catalogue_number']['element_label_type'] = 'strong';
  $handler->display->display_options['fields']['field_catalogue_number']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_catalogue_number']['element_default_classes'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_catalogue_number']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['field_catalogue_number']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_catalogue_number'] = array(
    'width' => 120,
    'sortable' => 1,
    'tab' => 'Brief',
    'filter' => 'textFilter'
  );
  /* Field: Content: Basis of record */
  $handler->display->display_options['fields']['field_basis_of_record']['id'] = 'field_basis_of_record';
  $handler->display->display_options['fields']['field_basis_of_record']['table'] = 'field_data_field_basis_of_record';
  $handler->display->display_options['fields']['field_basis_of_record']['field'] = 'field_basis_of_record';
  $handler->display->display_options['fields']['field_basis_of_record']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_basis_of_record']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_basis_of_record']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['element_type'] = '0';
  $handler->display->display_options['fields']['field_basis_of_record']['element_label_type'] = 'strong';
  $handler->display->display_options['fields']['field_basis_of_record']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_basis_of_record']['element_default_classes'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_basis_of_record']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['field_basis_of_record']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_basis_of_record'] = array(
    'width' => 120,
    'sortable' => 1,
    'tab' => 'Brief',
    'filter' => 'textFilter'
  );
  /* Field: Content: Date collected */
  $handler->display->display_options['fields']['field_date_collected']['id'] = 'field_date_collected';
  $handler->display->display_options['fields']['field_date_collected']['table'] = 'field_data_field_date_collected';
  $handler->display->display_options['fields']['field_date_collected']['field'] = 'field_date_collected';
  $handler->display->display_options['fields']['field_date_collected']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_date_collected']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_date_collected']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['element_type'] = '0';
  $handler->display->display_options['fields']['field_date_collected']['element_label_type'] = 'strong';
  $handler->display->display_options['fields']['field_date_collected']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_date_collected']['element_default_classes'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_date_collected']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['field_date_collected']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_date_collected'] = array(
    'width' => 120,
    'sortable' => 1,
    'tab' => 'Brief',
    'filter' => 'textFilter'
  );
  /* Field: Content: Map */
  $handler->display->display_options['fields']['field_map']['id'] = 'field_map';
  $handler->display->display_options['fields']['field_map']['table'] = 'field_data_field_map';
  $handler->display->display_options['fields']['field_map']['field'] = 'field_map';
  $handler->display->display_options['fields']['field_map']['relationship'] = 'field_location_nid';
  $handler->display->display_options['fields']['field_map']['label'] = 'Latitude';
  $handler->display->display_options['fields']['field_map']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_map']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_map']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_map']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_map']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['field_map']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['field_map']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_map']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_map']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_map']['alter']['more_link'] = 0;
  $handler->display->display_options['fields']['field_map']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_map']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_map']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_map']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_map']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_map']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_map']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_map']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['field_map']['click_sort_column'] = 'latitude';
  $handler->display->display_options['fields']['field_map']['type'] = 'gm3_latitude';
  $handler->display->display_options['fields']['field_map']['settings'] = array(
    'display_convex_hull' => FALSE,
  );
  $handler->display->display_options['fields']['field_map']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_map'] = array(
    'width' => 120,
    'sortable' => 1,
    'tab' => 'Brief',
    'filter' => 'textFilter'
  );
  /* Field: Content: Map */
  $handler->display->display_options['fields']['field_map_1']['id'] = 'field_map_1';
  $handler->display->display_options['fields']['field_map_1']['table'] = 'field_data_field_map';
  $handler->display->display_options['fields']['field_map_1']['field'] = 'field_map';
  $handler->display->display_options['fields']['field_map_1']['relationship'] = 'field_location_nid';
  $handler->display->display_options['fields']['field_map_1']['label'] = 'Longitude';
  $handler->display->display_options['fields']['field_map_1']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_map_1']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_map_1']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_map_1']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_map_1']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['field_map_1']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['field_map_1']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_map_1']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_map_1']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_map_1']['alter']['more_link'] = 0;
  $handler->display->display_options['fields']['field_map_1']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_map_1']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_map_1']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_map_1']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_map_1']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_map_1']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_map_1']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_map_1']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['field_map_1']['click_sort_column'] = 'latitude';
  $handler->display->display_options['fields']['field_map_1']['type'] = 'gm3_longitude';
  $handler->display->display_options['fields']['field_map_1']['settings'] = array(
    'display_convex_hull' => FALSE,
  );
  $handler->display->display_options['fields']['field_map_1']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_map_1'] = array(
    'width' => 120,
    'sortable' => 1,
    'tab' => 'Brief',
    'filter' => 'textFilter'
  );

// Full Tab for specimen_observation -------------
  
    /* Field: Content: Field collector */
    $handler->display->display_options['fields']['field_collector']['id'] = 'field_collector';
    $handler->display->display_options['fields']['field_collector']['table'] = 'field_data_field_collector';
    $handler->display->display_options['fields']['field_collector']['field'] = 'field_collector';
    $handler->display->display_options['fields']['field_collector']['alter']['alter_text'] = 0;
    $handler->display->display_options['fields']['field_collector']['alter']['make_link'] = 0;
    $handler->display->display_options['fields']['field_collector']['alter']['absolute'] = 0;
    $handler->display->display_options['fields']['field_collector']['alter']['external'] = 0;
    $handler->display->display_options['fields']['field_collector']['alter']['replace_spaces'] = 0;
    $handler->display->display_options['fields']['field_collector']['alter']['trim_whitespace'] = 0;
    $handler->display->display_options['fields']['field_collector']['alter']['nl2br'] = 0;
    $handler->display->display_options['fields']['field_collector']['alter']['word_boundary'] = 1;
    $handler->display->display_options['fields']['field_collector']['alter']['ellipsis'] = 1;
    $handler->display->display_options['fields']['field_collector']['alter']['strip_tags'] = 0;
    $handler->display->display_options['fields']['field_collector']['alter']['trim'] = 0;
    $handler->display->display_options['fields']['field_collector']['alter']['html'] = 0;
    $handler->display->display_options['fields']['field_collector']['element_type'] = '0';
    $handler->display->display_options['fields']['field_collector']['element_label_type'] = 'strong';
    $handler->display->display_options['fields']['field_collector']['element_label_colon'] = 1;
    $handler->display->display_options['fields']['field_collector']['element_default_classes'] = 0;
    $handler->display->display_options['fields']['field_collector']['hide_empty'] = 0;
    $handler->display->display_options['fields']['field_collector']['empty_zero'] = 0;
    $handler->display->display_options['fields']['field_collector']['hide_alter_empty'] = 1;
    $handler->display->display_options['fields']['field_collector']['field_api_classes'] = 0;
    $handler->display->display_options['style_options']['columns']['field_collector'] = array(
      'sortable' => 1,
      'tab' => 'Full',
      'filter' => 'textFilter'
    );
    /* Field: Content: Collector number */
    $handler->display->display_options['fields']['field_collector_number']['id'] = 'field_collector_number';
    $handler->display->display_options['fields']['field_collector_number']['table'] = 'field_data_field_collector_number';
    $handler->display->display_options['fields']['field_collector_number']['field'] = 'field_collector_number';
    $handler->display->display_options['fields']['field_collector_number']['alter']['alter_text'] = 0;
    $handler->display->display_options['fields']['field_collector_number']['alter']['make_link'] = 0;
    $handler->display->display_options['fields']['field_collector_number']['alter']['absolute'] = 0;
    $handler->display->display_options['fields']['field_collector_number']['alter']['external'] = 0;
    $handler->display->display_options['fields']['field_collector_number']['alter']['replace_spaces'] = 0;
    $handler->display->display_options['fields']['field_collector_number']['alter']['trim_whitespace'] = 0;
    $handler->display->display_options['fields']['field_collector_number']['alter']['nl2br'] = 0;
    $handler->display->display_options['fields']['field_collector_number']['alter']['word_boundary'] = 1;
    $handler->display->display_options['fields']['field_collector_number']['alter']['ellipsis'] = 1;
    $handler->display->display_options['fields']['field_collector_number']['alter']['strip_tags'] = 0;
    $handler->display->display_options['fields']['field_collector_number']['alter']['trim'] = 0;
    $handler->display->display_options['fields']['field_collector_number']['alter']['html'] = 0;
    $handler->display->display_options['fields']['field_collector_number']['element_type'] = '0';
    $handler->display->display_options['fields']['field_collector_number']['element_label_type'] = 'strong';
    $handler->display->display_options['fields']['field_collector_number']['element_label_colon'] = 1;
    $handler->display->display_options['fields']['field_collector_number']['element_default_classes'] = 0;
    $handler->display->display_options['fields']['field_collector_number']['hide_empty'] = 0;
    $handler->display->display_options['fields']['field_collector_number']['empty_zero'] = 0;
    $handler->display->display_options['fields']['field_collector_number']['hide_alter_empty'] = 1;
    $handler->display->display_options['fields']['field_collector_number']['field_api_classes'] = 0;
    $handler->display->display_options['style_options']['columns']['field_collector_number'] = array(
      'sortable' => 1,
      'tab' => 'Full',
      'filter' => 'textFilter'
    );
    /* Field: Content: Count */
    $handler->display->display_options['fields']['field_count']['id'] = 'field_count';
    $handler->display->display_options['fields']['field_count']['table'] = 'field_data_field_count';
    $handler->display->display_options['fields']['field_count']['field'] = 'field_count';
    $handler->display->display_options['fields']['field_count']['alter']['alter_text'] = 0;
    $handler->display->display_options['fields']['field_count']['alter']['make_link'] = 0;
    $handler->display->display_options['fields']['field_count']['alter']['absolute'] = 0;
    $handler->display->display_options['fields']['field_count']['alter']['external'] = 0;
    $handler->display->display_options['fields']['field_count']['alter']['replace_spaces'] = 0;
    $handler->display->display_options['fields']['field_count']['alter']['trim_whitespace'] = 0;
    $handler->display->display_options['fields']['field_count']['alter']['nl2br'] = 0;
    $handler->display->display_options['fields']['field_count']['alter']['word_boundary'] = 1;
    $handler->display->display_options['fields']['field_count']['alter']['ellipsis'] = 1;
    $handler->display->display_options['fields']['field_count']['alter']['strip_tags'] = 0;
    $handler->display->display_options['fields']['field_count']['alter']['trim'] = 0;
    $handler->display->display_options['fields']['field_count']['alter']['html'] = 0;
    $handler->display->display_options['fields']['field_count']['element_type'] = '0';
    $handler->display->display_options['fields']['field_count']['element_label_type'] = 'strong';
    $handler->display->display_options['fields']['field_count']['element_label_colon'] = 1;
    $handler->display->display_options['fields']['field_count']['element_default_classes'] = 0;
    $handler->display->display_options['fields']['field_count']['hide_empty'] = 0;
    $handler->display->display_options['fields']['field_count']['empty_zero'] = 0;
    $handler->display->display_options['fields']['field_count']['hide_alter_empty'] = 1;
    $handler->display->display_options['fields']['field_count']['field_api_classes'] = 0;
    $handler->display->display_options['style_options']['columns']['field_count'] = array(
      'sortable' => 1,
      'tab' => 'Full',
      'filter' => 'textFilter'
    );

    /* Field: Content: Date identified */
    $handler->display->display_options['fields']['field_date_identified']['id'] = 'field_date_identified';
    $handler->display->display_options['fields']['field_date_identified']['table'] = 'field_data_field_date_identified';
    $handler->display->display_options['fields']['field_date_identified']['field'] = 'field_date_identified';
    $handler->display->display_options['fields']['field_date_identified']['alter']['alter_text'] = 0;
    $handler->display->display_options['fields']['field_date_identified']['alter']['make_link'] = 0;
    $handler->display->display_options['fields']['field_date_identified']['alter']['absolute'] = 0;
    $handler->display->display_options['fields']['field_date_identified']['alter']['external'] = 0;
    $handler->display->display_options['fields']['field_date_identified']['alter']['replace_spaces'] = 0;
    $handler->display->display_options['fields']['field_date_identified']['alter']['trim_whitespace'] = 0;
    $handler->display->display_options['fields']['field_date_identified']['alter']['nl2br'] = 0;
    $handler->display->display_options['fields']['field_date_identified']['alter']['word_boundary'] = 1;
    $handler->display->display_options['fields']['field_date_identified']['alter']['ellipsis'] = 1;
    $handler->display->display_options['fields']['field_date_identified']['alter']['strip_tags'] = 0;
    $handler->display->display_options['fields']['field_date_identified']['alter']['trim'] = 0;
    $handler->display->display_options['fields']['field_date_identified']['alter']['html'] = 0;
    $handler->display->display_options['fields']['field_date_identified']['element_type'] = '0';
    $handler->display->display_options['fields']['field_date_identified']['element_label_type'] = 'strong';
    $handler->display->display_options['fields']['field_date_identified']['element_label_colon'] = 1;
    $handler->display->display_options['fields']['field_date_identified']['element_default_classes'] = 0;
    $handler->display->display_options['fields']['field_date_identified']['hide_empty'] = 0;
    $handler->display->display_options['fields']['field_date_identified']['empty_zero'] = 0;
    $handler->display->display_options['fields']['field_date_identified']['hide_alter_empty'] = 1;
    $handler->display->display_options['fields']['field_date_identified']['field_api_classes'] = 0;
    $handler->display->display_options['style_options']['columns']['field_date_identified'] = array(
      'sortable' => 1,
      'tab' => 'Full',
      'filter' => 'textFilter'
    );

    /* Field: Content: Notes */
    $handler->display->display_options['fields']['field_notes']['id'] = 'field_notes';
    $handler->display->display_options['fields']['field_notes']['table'] = 'field_data_field_notes';
    $handler->display->display_options['fields']['field_notes']['field'] = 'field_notes';
    $handler->display->display_options['fields']['field_notes']['alter']['alter_text'] = 0;
    $handler->display->display_options['fields']['field_notes']['alter']['make_link'] = 0;
    $handler->display->display_options['fields']['field_notes']['alter']['absolute'] = 0;
    $handler->display->display_options['fields']['field_notes']['alter']['external'] = 0;
    $handler->display->display_options['fields']['field_notes']['alter']['replace_spaces'] = 0;
    $handler->display->display_options['fields']['field_notes']['alter']['trim_whitespace'] = 0;
    $handler->display->display_options['fields']['field_notes']['alter']['nl2br'] = 0;
    $handler->display->display_options['fields']['field_notes']['alter']['word_boundary'] = 1;
    $handler->display->display_options['fields']['field_notes']['alter']['ellipsis'] = 1;
    $handler->display->display_options['fields']['field_notes']['alter']['strip_tags'] = 0;
    $handler->display->display_options['fields']['field_notes']['alter']['trim'] = 0;
    $handler->display->display_options['fields']['field_notes']['alter']['html'] = 0;
    $handler->display->display_options['fields']['field_notes']['element_type'] = '0';
    $handler->display->display_options['fields']['field_notes']['element_label_type'] = 'strong';
    $handler->display->display_options['fields']['field_notes']['element_label_colon'] = 1;
    $handler->display->display_options['fields']['field_notes']['element_default_classes'] = 0;
    $handler->display->display_options['fields']['field_notes']['hide_empty'] = 0;
    $handler->display->display_options['fields']['field_notes']['empty_zero'] = 0;
    $handler->display->display_options['fields']['field_notes']['hide_alter_empty'] = 1;
    $handler->display->display_options['fields']['field_notes']['field_api_classes'] = 0;
    $handler->display->display_options['style_options']['columns']['field_notes'] = array(
      'sortable' => 1,
      'tab' => 'Full',
      'filter' => 'textFilter'
    );

    /* Field: Content: Number */
    $handler->display->display_options['fields']['field_number']['id'] = 'field_number';
    $handler->display->display_options['fields']['field_number']['table'] = 'field_data_field_number';
    $handler->display->display_options['fields']['field_number']['field'] = 'field_number';
    $handler->display->display_options['fields']['field_number']['alter']['alter_text'] = 0;
    $handler->display->display_options['fields']['field_number']['alter']['make_link'] = 0;
    $handler->display->display_options['fields']['field_number']['alter']['absolute'] = 0;
    $handler->display->display_options['fields']['field_number']['alter']['external'] = 0;
    $handler->display->display_options['fields']['field_number']['alter']['replace_spaces'] = 0;
    $handler->display->display_options['fields']['field_number']['alter']['trim_whitespace'] = 0;
    $handler->display->display_options['fields']['field_number']['alter']['nl2br'] = 0;
    $handler->display->display_options['fields']['field_number']['alter']['word_boundary'] = 1;
    $handler->display->display_options['fields']['field_number']['alter']['ellipsis'] = 1;
    $handler->display->display_options['fields']['field_number']['alter']['strip_tags'] = 0;
    $handler->display->display_options['fields']['field_number']['alter']['trim'] = 0;
    $handler->display->display_options['fields']['field_number']['alter']['html'] = 0;
    $handler->display->display_options['fields']['field_number']['element_type'] = '0';
    $handler->display->display_options['fields']['field_number']['element_label_type'] = 'strong';
    $handler->display->display_options['fields']['field_number']['element_label_colon'] = 1;
    $handler->display->display_options['fields']['field_number']['element_default_classes'] = 0;
    $handler->display->display_options['fields']['field_number']['hide_empty'] = 0;
    $handler->display->display_options['fields']['field_number']['empty_zero'] = 0;
    $handler->display->display_options['fields']['field_number']['hide_alter_empty'] = 1;
    $handler->display->display_options['fields']['field_number']['field_api_classes'] = 0;
    $handler->display->display_options['style_options']['columns']['field_number'] = array(
      'sortable' => 1,
      'tab' => 'Full',
      'filter' => 'textFilter'
    );

    /* Field: Content: Genbank Number */
    $handler->display->display_options['fields']['field_genbank_number']['id'] = 'field_genbank_number';
    $handler->display->display_options['fields']['field_genbank_number']['table'] = 'field_data_field_genbank_number';
    $handler->display->display_options['fields']['field_genbank_number']['field'] = 'field_genbank_number';
    $handler->display->display_options['fields']['field_genbank_number']['alter']['alter_text'] = 0;
    $handler->display->display_options['fields']['field_genbank_number']['alter']['make_link'] = 0;
    $handler->display->display_options['fields']['field_genbank_number']['alter']['absolute'] = 0;
    $handler->display->display_options['fields']['field_genbank_number']['alter']['external'] = 0;
    $handler->display->display_options['fields']['field_genbank_number']['alter']['replace_spaces'] = 0;
    $handler->display->display_options['fields']['field_genbank_number']['alter']['trim_whitespace'] = 0;
    $handler->display->display_options['fields']['field_genbank_number']['alter']['nl2br'] = 0;
    $handler->display->display_options['fields']['field_genbank_number']['alter']['word_boundary'] = 1;
    $handler->display->display_options['fields']['field_genbank_number']['alter']['ellipsis'] = 1;
    $handler->display->display_options['fields']['field_genbank_number']['alter']['strip_tags'] = 0;
    $handler->display->display_options['fields']['field_genbank_number']['alter']['trim'] = 0;
    $handler->display->display_options['fields']['field_genbank_number']['alter']['html'] = 0;
    $handler->display->display_options['fields']['field_genbank_number']['element_type'] = '0';
    $handler->display->display_options['fields']['field_genbank_number']['element_label_type'] = 'strong';
    $handler->display->display_options['fields']['field_genbank_number']['element_label_colon'] = 1;
    $handler->display->display_options['fields']['field_genbank_number']['element_default_classes'] = 0;
    $handler->display->display_options['fields']['field_genbank_number']['hide_empty'] = 0;
    $handler->display->display_options['fields']['field_genbank_number']['empty_zero'] = 0;
    $handler->display->display_options['fields']['field_genbank_number']['hide_alter_empty'] = 1;
    $handler->display->display_options['fields']['field_genbank_number']['field_api_classes'] = 0;
    $handler->display->display_options['style_options']['columns']['field_genbank_number'] = array(
      'sortable' => 1,
      'tab' => 'Full',
      'filter' => 'textFilter'
    );

    /* Field: Content: Identification qualifier */
    $handler->display->display_options['fields']['field_identification_qualifier']['id'] = 'field_identification_qualifier';
    $handler->display->display_options['fields']['field_identification_qualifier']['table'] = 'field_data_field_identification_qualifier';
    $handler->display->display_options['fields']['field_identification_qualifier']['field'] = 'field_identification_qualifier';
    $handler->display->display_options['fields']['field_identification_qualifier']['alter']['alter_text'] = 0;
    $handler->display->display_options['fields']['field_identification_qualifier']['alter']['make_link'] = 0;
    $handler->display->display_options['fields']['field_identification_qualifier']['alter']['absolute'] = 0;
    $handler->display->display_options['fields']['field_identification_qualifier']['alter']['external'] = 0;
    $handler->display->display_options['fields']['field_identification_qualifier']['alter']['replace_spaces'] = 0;
    $handler->display->display_options['fields']['field_identification_qualifier']['alter']['trim_whitespace'] = 0;
    $handler->display->display_options['fields']['field_identification_qualifier']['alter']['nl2br'] = 0;
    $handler->display->display_options['fields']['field_identification_qualifier']['alter']['word_boundary'] = 1;
    $handler->display->display_options['fields']['field_identification_qualifier']['alter']['ellipsis'] = 1;
    $handler->display->display_options['fields']['field_identification_qualifier']['alter']['strip_tags'] = 0;
    $handler->display->display_options['fields']['field_identification_qualifier']['alter']['trim'] = 0;
    $handler->display->display_options['fields']['field_identification_qualifier']['alter']['html'] = 0;
    $handler->display->display_options['fields']['field_identification_qualifier']['element_type'] = '0';
    $handler->display->display_options['fields']['field_identification_qualifier']['element_label_type'] = 'strong';
    $handler->display->display_options['fields']['field_identification_qualifier']['element_label_colon'] = 1;
    $handler->display->display_options['fields']['field_identification_qualifier']['element_default_classes'] = 0;
    $handler->display->display_options['fields']['field_identification_qualifier']['hide_empty'] = 0;
    $handler->display->display_options['fields']['field_identification_qualifier']['empty_zero'] = 0;
    $handler->display->display_options['fields']['field_identification_qualifier']['hide_alter_empty'] = 1;
    $handler->display->display_options['fields']['field_identification_qualifier']['field_api_classes'] = 0;
    $handler->display->display_options['style_options']['columns']['field_identification_qualifier'] = array(
      'sortable' => 1,
      'tab' => 'Full',
      'filter' => 'textFilter'
    );

    /* Field: Content: Identified by */
    $handler->display->display_options['fields']['field_identified_by']['id'] = 'field_identified_by';
    $handler->display->display_options['fields']['field_identified_by']['table'] = 'field_data_field_identified_by';
    $handler->display->display_options['fields']['field_identified_by']['field'] = 'field_identified_by';
    $handler->display->display_options['fields']['field_identified_by']['alter']['alter_text'] = 0;
    $handler->display->display_options['fields']['field_identified_by']['alter']['make_link'] = 0;
    $handler->display->display_options['fields']['field_identified_by']['alter']['absolute'] = 0;
    $handler->display->display_options['fields']['field_identified_by']['alter']['external'] = 0;
    $handler->display->display_options['fields']['field_identified_by']['alter']['replace_spaces'] = 0;
    $handler->display->display_options['fields']['field_identified_by']['alter']['trim_whitespace'] = 0;
    $handler->display->display_options['fields']['field_identified_by']['alter']['nl2br'] = 0;
    $handler->display->display_options['fields']['field_identified_by']['alter']['word_boundary'] = 1;
    $handler->display->display_options['fields']['field_identified_by']['alter']['ellipsis'] = 1;
    $handler->display->display_options['fields']['field_identified_by']['alter']['strip_tags'] = 0;
    $handler->display->display_options['fields']['field_identified_by']['alter']['trim'] = 0;
    $handler->display->display_options['fields']['field_identified_by']['alter']['html'] = 0;
    $handler->display->display_options['fields']['field_identified_by']['element_type'] = '0';
    $handler->display->display_options['fields']['field_identified_by']['element_label_type'] = 'strong';
    $handler->display->display_options['fields']['field_identified_by']['element_label_colon'] = 1;
    $handler->display->display_options['fields']['field_identified_by']['element_default_classes'] = 0;
    $handler->display->display_options['fields']['field_identified_by']['hide_empty'] = 0;
    $handler->display->display_options['fields']['field_identified_by']['empty_zero'] = 0;
    $handler->display->display_options['fields']['field_identified_by']['hide_alter_empty'] = 1;
    $handler->display->display_options['fields']['field_identified_by']['field_api_classes'] = 0;
    $handler->display->display_options['style_options']['columns']['field_identified_by'] = array(
      'sortable' => 1,
      'tab' => 'Full',
      'filter' => 'textFilter'
    );

    /* Field: Content: Lifestage */
    $handler->display->display_options['fields']['field_lifestage']['id'] = 'field_lifestage';
    $handler->display->display_options['fields']['field_lifestage']['table'] = 'field_data_field_lifestage';
    $handler->display->display_options['fields']['field_lifestage']['field'] = 'field_lifestage';
    $handler->display->display_options['fields']['field_lifestage']['alter']['alter_text'] = 0;
    $handler->display->display_options['fields']['field_lifestage']['alter']['make_link'] = 0;
    $handler->display->display_options['fields']['field_lifestage']['alter']['absolute'] = 0;
    $handler->display->display_options['fields']['field_lifestage']['alter']['external'] = 0;
    $handler->display->display_options['fields']['field_lifestage']['alter']['replace_spaces'] = 0;
    $handler->display->display_options['fields']['field_lifestage']['alter']['trim_whitespace'] = 0;
    $handler->display->display_options['fields']['field_lifestage']['alter']['nl2br'] = 0;
    $handler->display->display_options['fields']['field_lifestage']['alter']['word_boundary'] = 1;
    $handler->display->display_options['fields']['field_lifestage']['alter']['ellipsis'] = 1;
    $handler->display->display_options['fields']['field_lifestage']['alter']['strip_tags'] = 0;
    $handler->display->display_options['fields']['field_lifestage']['alter']['trim'] = 0;
    $handler->display->display_options['fields']['field_lifestage']['alter']['html'] = 0;
    $handler->display->display_options['fields']['field_lifestage']['element_type'] = '0';
    $handler->display->display_options['fields']['field_lifestage']['element_label_type'] = 'strong';
    $handler->display->display_options['fields']['field_lifestage']['element_label_colon'] = 1;
    $handler->display->display_options['fields']['field_lifestage']['element_default_classes'] = 0;
    $handler->display->display_options['fields']['field_lifestage']['hide_empty'] = 0;
    $handler->display->display_options['fields']['field_lifestage']['empty_zero'] = 0;
    $handler->display->display_options['fields']['field_lifestage']['hide_alter_empty'] = 1;
    $handler->display->display_options['fields']['field_lifestage']['field_api_classes'] = 0;
    $handler->display->display_options['style_options']['columns']['field_lifestage'] = array(
      'sortable' => 1,
      'tab' => 'Full',
      'filter' => 'textFilter'
    );

    /* Field: Content: Other catalogue numbers */
    $handler->display->display_options['fields']['field_other_catalogue_numbers']['id'] = 'field_other_catalogue_numbers';
    $handler->display->display_options['fields']['field_other_catalogue_numbers']['table'] = 'field_data_field_other_catalogue_numbers';
    $handler->display->display_options['fields']['field_other_catalogue_numbers']['field'] = 'field_other_catalogue_numbers';
    $handler->display->display_options['fields']['field_other_catalogue_numbers']['alter']['alter_text'] = 0;
    $handler->display->display_options['fields']['field_other_catalogue_numbers']['alter']['make_link'] = 0;
    $handler->display->display_options['fields']['field_other_catalogue_numbers']['alter']['absolute'] = 0;
    $handler->display->display_options['fields']['field_other_catalogue_numbers']['alter']['external'] = 0;
    $handler->display->display_options['fields']['field_other_catalogue_numbers']['alter']['replace_spaces'] = 0;
    $handler->display->display_options['fields']['field_other_catalogue_numbers']['alter']['trim_whitespace'] = 0;
    $handler->display->display_options['fields']['field_other_catalogue_numbers']['alter']['nl2br'] = 0;
    $handler->display->display_options['fields']['field_other_catalogue_numbers']['alter']['word_boundary'] = 1;
    $handler->display->display_options['fields']['field_other_catalogue_numbers']['alter']['ellipsis'] = 1;
    $handler->display->display_options['fields']['field_other_catalogue_numbers']['alter']['strip_tags'] = 0;
    $handler->display->display_options['fields']['field_other_catalogue_numbers']['alter']['trim'] = 0;
    $handler->display->display_options['fields']['field_other_catalogue_numbers']['alter']['html'] = 0;
    $handler->display->display_options['fields']['field_other_catalogue_numbers']['element_type'] = '0';
    $handler->display->display_options['fields']['field_other_catalogue_numbers']['element_label_type'] = 'strong';
    $handler->display->display_options['fields']['field_other_catalogue_numbers']['element_label_colon'] = 1;
    $handler->display->display_options['fields']['field_other_catalogue_numbers']['element_default_classes'] = 0;
    $handler->display->display_options['fields']['field_other_catalogue_numbers']['hide_empty'] = 0;
    $handler->display->display_options['fields']['field_other_catalogue_numbers']['empty_zero'] = 0;
    $handler->display->display_options['fields']['field_other_catalogue_numbers']['hide_alter_empty'] = 1;
    $handler->display->display_options['fields']['field_other_catalogue_numbers']['field_api_classes'] = 0;
    $handler->display->display_options['style_options']['columns']['field_other_catalogue_numbers'] = array(
      'sortable' => 1,
      'tab' => 'Full',
      'filter' => 'textFilter'
    );

    /* Field: Content: Remarks */
    $handler->display->display_options['fields']['field_remarks']['id'] = 'field_remarks';
    $handler->display->display_options['fields']['field_remarks']['table'] = 'field_data_field_remarks';
    $handler->display->display_options['fields']['field_remarks']['field'] = 'field_remarks';
    $handler->display->display_options['fields']['field_remarks']['alter']['alter_text'] = 0;
    $handler->display->display_options['fields']['field_remarks']['alter']['make_link'] = 0;
    $handler->display->display_options['fields']['field_remarks']['alter']['absolute'] = 0;
    $handler->display->display_options['fields']['field_remarks']['alter']['external'] = 0;
    $handler->display->display_options['fields']['field_remarks']['alter']['replace_spaces'] = 0;
    $handler->display->display_options['fields']['field_remarks']['alter']['trim_whitespace'] = 0;
    $handler->display->display_options['fields']['field_remarks']['alter']['nl2br'] = 0;
    $handler->display->display_options['fields']['field_remarks']['alter']['word_boundary'] = 1;
    $handler->display->display_options['fields']['field_remarks']['alter']['ellipsis'] = 1;
    $handler->display->display_options['fields']['field_remarks']['alter']['strip_tags'] = 0;
    $handler->display->display_options['fields']['field_remarks']['alter']['trim'] = 0;
    $handler->display->display_options['fields']['field_remarks']['alter']['html'] = 0;
    $handler->display->display_options['fields']['field_remarks']['element_type'] = '0';
    $handler->display->display_options['fields']['field_remarks']['element_label_type'] = 'strong';
    $handler->display->display_options['fields']['field_remarks']['element_label_colon'] = 1;
    $handler->display->display_options['fields']['field_remarks']['element_default_classes'] = 0;
    $handler->display->display_options['fields']['field_remarks']['hide_empty'] = 0;
    $handler->display->display_options['fields']['field_remarks']['empty_zero'] = 0;
    $handler->display->display_options['fields']['field_remarks']['hide_alter_empty'] = 1;
    $handler->display->display_options['fields']['field_remarks']['field_api_classes'] = 0;
    $handler->display->display_options['style_options']['columns']['field_remarks'] = array(
      'sortable' => 1,
      'tab' => 'Full',
      'filter' => 'textFilter'
    );

    /* Field: Content: Sex */
    $handler->display->display_options['fields']['field_sex']['id'] = 'field_sex';
    $handler->display->display_options['fields']['field_sex']['table'] = 'field_data_field_sex';
    $handler->display->display_options['fields']['field_sex']['field'] = 'field_sex';
    $handler->display->display_options['fields']['field_sex']['alter']['alter_text'] = 0;
    $handler->display->display_options['fields']['field_sex']['alter']['make_link'] = 0;
    $handler->display->display_options['fields']['field_sex']['alter']['absolute'] = 0;
    $handler->display->display_options['fields']['field_sex']['alter']['external'] = 0;
    $handler->display->display_options['fields']['field_sex']['alter']['replace_spaces'] = 0;
    $handler->display->display_options['fields']['field_sex']['alter']['trim_whitespace'] = 0;
    $handler->display->display_options['fields']['field_sex']['alter']['nl2br'] = 0;
    $handler->display->display_options['fields']['field_sex']['alter']['word_boundary'] = 1;
    $handler->display->display_options['fields']['field_sex']['alter']['ellipsis'] = 1;
    $handler->display->display_options['fields']['field_sex']['alter']['strip_tags'] = 0;
    $handler->display->display_options['fields']['field_sex']['alter']['trim'] = 0;
    $handler->display->display_options['fields']['field_sex']['alter']['html'] = 0;
    $handler->display->display_options['fields']['field_sex']['element_type'] = '0';
    $handler->display->display_options['fields']['field_sex']['element_label_type'] = 'strong';
    $handler->display->display_options['fields']['field_sex']['element_label_colon'] = 1;
    $handler->display->display_options['fields']['field_sex']['element_default_classes'] = 0;
    $handler->display->display_options['fields']['field_sex']['hide_empty'] = 0;
    $handler->display->display_options['fields']['field_sex']['empty_zero'] = 0;
    $handler->display->display_options['fields']['field_sex']['hide_alter_empty'] = 1;
    $handler->display->display_options['fields']['field_sex']['field_api_classes'] = 0;
    $handler->display->display_options['style_options']['columns']['field_sex'] = array(
      'sortable' => 1,
      'tab' => 'Full',
      'filter' => 'textFilter'
    );

    /* Field: Content: Type status */
    $handler->display->display_options['fields']['field_type_status']['id'] = 'field_type_status';
    $handler->display->display_options['fields']['field_type_status']['table'] = 'field_data_field_type_status';
    $handler->display->display_options['fields']['field_type_status']['field'] = 'field_type_status';
    $handler->display->display_options['fields']['field_type_status']['alter']['alter_text'] = 0;
    $handler->display->display_options['fields']['field_type_status']['alter']['make_link'] = 0;
    $handler->display->display_options['fields']['field_type_status']['alter']['absolute'] = 0;
    $handler->display->display_options['fields']['field_type_status']['alter']['external'] = 0;
    $handler->display->display_options['fields']['field_type_status']['alter']['replace_spaces'] = 0;
    $handler->display->display_options['fields']['field_type_status']['alter']['trim_whitespace'] = 0;
    $handler->display->display_options['fields']['field_type_status']['alter']['nl2br'] = 0;
    $handler->display->display_options['fields']['field_type_status']['alter']['word_boundary'] = 1;
    $handler->display->display_options['fields']['field_type_status']['alter']['ellipsis'] = 1;
    $handler->display->display_options['fields']['field_type_status']['alter']['strip_tags'] = 0;
    $handler->display->display_options['fields']['field_type_status']['alter']['trim'] = 0;
    $handler->display->display_options['fields']['field_type_status']['alter']['html'] = 0;
    $handler->display->display_options['fields']['field_type_status']['element_type'] = '0';
    $handler->display->display_options['fields']['field_type_status']['element_label_type'] = 'strong';
    $handler->display->display_options['fields']['field_type_status']['element_label_colon'] = 1;
    $handler->display->display_options['fields']['field_type_status']['element_default_classes'] = 0;
    $handler->display->display_options['fields']['field_type_status']['hide_empty'] = 0;
    $handler->display->display_options['fields']['field_type_status']['empty_zero'] = 0;
    $handler->display->display_options['fields']['field_type_status']['hide_alter_empty'] = 1;
    $handler->display->display_options['fields']['field_type_status']['field_api_classes'] = 0;
    $handler->display->display_options['style_options']['columns']['field_type_status'] = array(
      'sortable' => 1,
      'tab' => 'Full',
      'filter' => 'textFilter'
    );

// Full Location Tab

  /* Field: Fields: Continent/Ocean */
  $handler->display->display_options['fields']['field_continent_or_ocean']['id'] = 'field_continent_or_ocean';
  $handler->display->display_options['fields']['field_continent_or_ocean']['table'] = 'field_data_field_continent_or_ocean';
  $handler->display->display_options['fields']['field_continent_or_ocean']['field'] = 'field_continent_or_ocean';
  $handler->display->display_options['fields']['field_continent_or_ocean']['relationship'] = 'field_location_nid';
  $handler->display->display_options['fields']['field_continent_or_ocean']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_continent_or_ocean']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_continent_or_ocean']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_continent_or_ocean']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_continent_or_ocean']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_continent_or_ocean']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_continent_or_ocean']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_continent_or_ocean']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_continent_or_ocean']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_continent_or_ocean']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_continent_or_ocean']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_continent_or_ocean']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_continent_or_ocean']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_continent_or_ocean']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_continent_or_ocean']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_continent_or_ocean'] = array(
    'sortable' => 1,
    'tab' => 'Full',
    'filter' => 'textFilter'
  );
  /* Field: Fields: Coordinate uncertainty in meters */
  $handler->display->display_options['fields']['field_coordinate_uncertainty']['id'] = 'field_coordinate_uncertainty';
  $handler->display->display_options['fields']['field_coordinate_uncertainty']['table'] = 'field_data_field_coordinate_uncertainty';
  $handler->display->display_options['fields']['field_coordinate_uncertainty']['field'] = 'field_coordinate_uncertainty';
  $handler->display->display_options['fields']['field_coordinate_uncertainty']['relationship'] = 'field_location_nid';
  $handler->display->display_options['fields']['field_coordinate_uncertainty']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_coordinate_uncertainty']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_coordinate_uncertainty']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_coordinate_uncertainty']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_coordinate_uncertainty']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_coordinate_uncertainty']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_coordinate_uncertainty']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_coordinate_uncertainty']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_coordinate_uncertainty']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_coordinate_uncertainty']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_coordinate_uncertainty']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_coordinate_uncertainty']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_coordinate_uncertainty']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_coordinate_uncertainty']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_coordinate_uncertainty']['settings'] = array(
    'thousand_separator' => ' ',
    'prefix_suffix' => 1
  );
  $handler->display->display_options['fields']['field_coordinate_uncertainty']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_coordinate_uncertainty'] = array(
    'sortable' => 1,
    'tab' => 'Full',
    'filter' => 'textFilter'
  );
  /* Field: Fields: County */
  $handler->display->display_options['fields']['field_county']['id'] = 'field_county';
  $handler->display->display_options['fields']['field_county']['table'] = 'field_data_field_county';
  $handler->display->display_options['fields']['field_county']['field'] = 'field_county';
  $handler->display->display_options['fields']['field_county']['relationship'] = 'field_location_nid';
  $handler->display->display_options['fields']['field_county']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_county']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_county']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_county']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_county']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_county']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_county']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_county']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_county']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_county']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_county']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_county']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_county']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_county']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_county']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_county'] = array(
    'sortable' => 1,
    'tab' => 'Full',
    'filter' => 'textFilter'
  );
  /* Field: Fields: Geodetic datum */
  $handler->display->display_options['fields']['field_geodetic_datum']['id'] = 'field_geodetic_datum';
  $handler->display->display_options['fields']['field_geodetic_datum']['table'] = 'field_data_field_geodetic_datum';
  $handler->display->display_options['fields']['field_geodetic_datum']['field'] = 'field_geodetic_datum';
  $handler->display->display_options['fields']['field_geodetic_datum']['relationship'] = 'field_location_nid';
  $handler->display->display_options['fields']['field_geodetic_datum']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_geodetic_datum']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_geodetic_datum']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_geodetic_datum']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_geodetic_datum']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_geodetic_datum']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_geodetic_datum']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_geodetic_datum']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_geodetic_datum']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_geodetic_datum']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_geodetic_datum']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_geodetic_datum']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_geodetic_datum']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_geodetic_datum']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_geodetic_datum']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_geodetic_datum'] = array(
    'sortable' => 1,
    'tab' => 'Full',
    'filter' => 'textFilter'
  );
  /* Field: Fields: Georeference protocol */
  $handler->display->display_options['fields']['field_georeference_protocol']['id'] = 'field_georeference_protocol';
  $handler->display->display_options['fields']['field_georeference_protocol']['table'] = 'field_data_field_georeference_protocol';
  $handler->display->display_options['fields']['field_georeference_protocol']['field'] = 'field_georeference_protocol';
  $handler->display->display_options['fields']['field_georeference_protocol']['relationship'] = 'field_location_nid';
  $handler->display->display_options['fields']['field_georeference_protocol']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_georeference_protocol']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_georeference_protocol']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_georeference_protocol']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_georeference_protocol']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_georeference_protocol']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_georeference_protocol']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_georeference_protocol']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_georeference_protocol']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_georeference_protocol']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_georeference_protocol']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_georeference_protocol']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_georeference_protocol']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_georeference_protocol']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_georeference_protocol']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_georeference_protocol'] = array(
    'sortable' => 1,
    'tab' => 'Full',
    'filter' => 'textFilter'
  );
  /* Field: Fields: Georeference remarks */
  $handler->display->display_options['fields']['field_georeference_remarks']['id'] = 'field_georeference_remarks';
  $handler->display->display_options['fields']['field_georeference_remarks']['table'] = 'field_data_field_georeference_remarks';
  $handler->display->display_options['fields']['field_georeference_remarks']['field'] = 'field_georeference_remarks';
  $handler->display->display_options['fields']['field_georeference_remarks']['relationship'] = 'field_location_nid';
  $handler->display->display_options['fields']['field_georeference_remarks']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_georeference_remarks']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_georeference_remarks']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_georeference_remarks']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_georeference_remarks']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_georeference_remarks']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_georeference_remarks']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_georeference_remarks']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_georeference_remarks']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_georeference_remarks']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_georeference_remarks']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_georeference_remarks']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_georeference_remarks']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_georeference_remarks']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_georeference_remarks']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_georeference_remarks'] = array(
    'sortable' => 1,
    'tab' => 'Full',
    'filter' => 'textFilter'
  );
  /* Field: Fields: Island */
  $handler->display->display_options['fields']['field_island']['id'] = 'field_island';
  $handler->display->display_options['fields']['field_island']['table'] = 'field_data_field_island';
  $handler->display->display_options['fields']['field_island']['field'] = 'field_island';
  $handler->display->display_options['fields']['field_island']['relationship'] = 'field_location_nid';
  $handler->display->display_options['fields']['field_island']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_island']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_island']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_island']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_island']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_island']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_island']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_island']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_island']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_island']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_island']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_island']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_island']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_island']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_island']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_island'] = array(
    'sortable' => 1,
    'tab' => 'Full',
    'filter' => 'textFilter'
  );
  /* Field: Fields: Locality */
  $handler->display->display_options['fields']['field_locality']['id'] = 'field_locality';
  $handler->display->display_options['fields']['field_locality']['table'] = 'field_data_field_locality';
  $handler->display->display_options['fields']['field_locality']['field'] = 'field_locality';
  $handler->display->display_options['fields']['field_locality']['relationship'] = 'field_location_nid';
  $handler->display->display_options['fields']['field_locality']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_locality']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_locality']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_locality']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_locality']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_locality']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_locality']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_locality']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_locality']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_locality']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_locality']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_locality']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_locality']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_locality']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_locality']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_locality'] = array(
    'sortable' => 1,
    'tab' => 'Full',
    'filter' => 'textFilter'
  );
  /* Field: Fields: Maximum depth */
  $handler->display->display_options['fields']['field_max_depth']['id'] = 'field_max_depth';
  $handler->display->display_options['fields']['field_max_depth']['table'] = 'field_data_field_max_depth';
  $handler->display->display_options['fields']['field_max_depth']['field'] = 'field_max_depth';
  $handler->display->display_options['fields']['field_max_depth']['relationship'] = 'field_location_nid';
  $handler->display->display_options['fields']['field_max_depth']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_max_depth']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_max_depth']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_max_depth']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_max_depth']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_max_depth']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_max_depth']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_max_depth']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_max_depth']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_max_depth']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_max_depth']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_max_depth']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_max_depth']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_max_depth']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_max_depth']['settings'] = array(
    'thousand_separator' => ' ',
    'prefix_suffix' => 1
  );
  $handler->display->display_options['fields']['field_max_depth']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_max_depth'] = array(
    'sortable' => 1,
    'tab' => 'Full',
    'filter' => 'textFilter'
  );
  /* Field: Fields: Maximum elevation */
  $handler->display->display_options['fields']['field_max_elevation']['id'] = 'field_max_elevation';
  $handler->display->display_options['fields']['field_max_elevation']['table'] = 'field_data_field_max_elevation';
  $handler->display->display_options['fields']['field_max_elevation']['field'] = 'field_max_elevation';
  $handler->display->display_options['fields']['field_max_elevation']['relationship'] = 'field_location_nid';
  $handler->display->display_options['fields']['field_max_elevation']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_max_elevation']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_max_elevation']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_max_elevation']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_max_elevation']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_max_elevation']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_max_elevation']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_max_elevation']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_max_elevation']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_max_elevation']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_max_elevation']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_max_elevation']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_max_elevation']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_max_elevation']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_max_elevation']['settings'] = array(
    'thousand_separator' => ' ',
    'prefix_suffix' => 1
  );
  $handler->display->display_options['style_options']['columns']['field_max_elevation'] = array(
    'sortable' => 1,
    'tab' => 'Full',
    'filter' => 'textFilter'
  );
  $handler->display->display_options['fields']['field_max_elevation']['field_api_classes'] = 0;
  /* Field: Fields: Minimum depth */
  $handler->display->display_options['fields']['field_min_depth']['id'] = 'field_min_depth';
  $handler->display->display_options['fields']['field_min_depth']['table'] = 'field_data_field_min_depth';
  $handler->display->display_options['fields']['field_min_depth']['field'] = 'field_min_depth';
  $handler->display->display_options['fields']['field_min_depth']['relationship'] = 'field_location_nid';
  $handler->display->display_options['fields']['field_min_depth']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_min_depth']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_min_depth']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_min_depth']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_min_depth']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_min_depth']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_min_depth']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_min_depth']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_min_depth']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_min_depth']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_min_depth']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_min_depth']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_min_depth']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_min_depth']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_min_depth']['settings'] = array(
    'thousand_separator' => ' ',
    'prefix_suffix' => 1
  );
  $handler->display->display_options['style_options']['columns']['field_min_depth'] = array(
    'sortable' => 1,
    'tab' => 'Full',
    'filter' => 'textFilter'
  );
  $handler->display->display_options['fields']['field_min_depth']['field_api_classes'] = 0;
  /* Field: Fields: Minimum elevation */
  $handler->display->display_options['fields']['field_min_elevation']['id'] = 'field_min_elevation';
  $handler->display->display_options['fields']['field_min_elevation']['table'] = 'field_data_field_min_elevation';
  $handler->display->display_options['fields']['field_min_elevation']['field'] = 'field_min_elevation';
  $handler->display->display_options['fields']['field_min_elevation']['relationship'] = 'field_location_nid';
  $handler->display->display_options['fields']['field_min_elevation']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_min_elevation']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_min_elevation']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_min_elevation']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_min_elevation']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_min_elevation']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_min_elevation']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_min_elevation']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_min_elevation']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_min_elevation']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_min_elevation']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_min_elevation']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_min_elevation']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_min_elevation']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_min_elevation']['settings'] = array(
    'thousand_separator' => ' ',
    'prefix_suffix' => 1
  );
  $handler->display->display_options['fields']['field_min_elevation']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_min_elevation'] = array(
    'sortable' => 1,
    'tab' => 'Full',
    'filter' => 'textFilter'
  );
  /* Field: Fields: State/Province */
  $handler->display->display_options['fields']['field_state_province']['id'] = 'field_state_province';
  $handler->display->display_options['fields']['field_state_province']['table'] = 'field_data_field_state_province';
  $handler->display->display_options['fields']['field_state_province']['field'] = 'field_state_province';
  $handler->display->display_options['fields']['field_state_province']['relationship'] = 'field_location_nid';
  $handler->display->display_options['fields']['field_state_province']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_state_province']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_state_province']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_state_province']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_state_province']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_state_province']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_state_province']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_state_province']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_state_province']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_state_province']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_state_province']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_state_province']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_state_province']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_state_province']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_state_province']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_state_province'] = array(
    'sortable' => 1,
    'tab' => 'Full',
    'filter' => 'textFilter'
  );
  /* Field: Fields: Verbatim Coordinate System */
  $handler->display->display_options['fields']['field_coordinate_system']['id'] = 'field_coordinate_system';
  $handler->display->display_options['fields']['field_coordinate_system']['table'] = 'field_data_field_coordinate_system';
  $handler->display->display_options['fields']['field_coordinate_system']['field'] = 'field_coordinate_system';
  $handler->display->display_options['fields']['field_coordinate_system']['relationship'] = 'field_location_nid';
  $handler->display->display_options['fields']['field_coordinate_system']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_coordinate_system']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_coordinate_system']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_coordinate_system']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_coordinate_system']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_coordinate_system']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_coordinate_system']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_coordinate_system']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_coordinate_system']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_coordinate_system']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_coordinate_system']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_coordinate_system']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_coordinate_system']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_coordinate_system']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_coordinate_system']['field_api_classes'] = 0;
  $handler->display->display_options['style_options']['columns']['field_coordinate_system'] = array(
    'sortable' => 1,
    'tab' => 'Full',
    'filter' => 'textFilter'
  );
}

