<?php

include_once ('feeds_xlsimages.features.inc');

/**
 * Implementation of hook_feeds_plugins().
 *
 * To register the use of a new Processor the RemoteImageProcessor
 */
function feeds_xlsimages_feeds_plugins() {
  $info = array();
    $info['RemoteImageProcessor'] = array(
    'name' => 'Remote Image Processor',
    'description' => 'Download and agregate images.',
    'handler' => array(
      'parent' => 'FeedsProcessor', // A plugin needs to derive either directly or indirectly from FeedsFetcher, FeedsParser or FeedsProcessor.
      'class' => 'RemoteImageProcessor',
      'file' => 'RemoteImageProcessor.inc',
      'path' => drupal_get_path('module', 'feeds_xlsimages') . '/includes',
    ),
  );
  return $info;
}

/**
 * Implementation of the hook_enable
 */
function feeds_xlsimages_enable() {
  //clear the cache to display in Feeds as available plugin.
  cache_clear_all('plugins:feeds:plugins', 'cache');
}

/**
 * Implementation of hook_silver
 */
function feeds_xlsimages_silver() {
  return array(
    array(
      'type' => 'Nodes',
      'name' => 'Darwin Core Archive Import',
      'access arguments' => array(
        'administer feeds'
      ),
      'form_id' => 'feeds_xlsimages_primary_form'
    )
  );
}
