<?php

/**
 * @file
 * gm3_field_tweaks.module
 *
 * Implements the hooks for a couple of formatters to be added to the
 *  gm3_field module
 */


/**
 * Implements hook_theme
 *
 * To add some text formatters for latitude and longitude
 */
function gm3_field_tweaks_theme(){
  return Array(
    'gm3_short_text' => array(
      'variables' => array(
        'data' => array()
      )
    ),
    'gm3_latitude_text' => array(
      'variables' => array(
        'data' => array()
      )
    ),
    'gm3_longitude_text' => array(
      'variables' => array(
        'data' => array()
      )
    ),
    'short_text' => array(
      'variables' => array(
        'data' => array()
      )
    ),
    'latitude_text' => array(
      'variables' => array(
        'data' => array()
      )
    ),
    'longitude_text' => array(
      'variables' => array(
        'data' => array()
      )
    )
  );
}


/**
 * Implementation of hook_field_widget_info
 *
 * To Add the definitions of the text formatters for the
 * widget of the field.
 */
function gm3_field_tweaks_field_widget_info(){
  return array(
    'gm3_short_text' => array(
      'label' => t('Geo: Point short text'),
      'description' => t('Latitude/Longitude pairs entered into a text box'),
      'field types' => array(
        'gm3_point'
      )
    ),
    'gm3_latitude_text' => array(
      'label' => t('Geo: Point that only show latitude'),
      'description' => t('Latitude entered into a text box'),
      'field types' => array(
        'gm3_point'
      )
    ),
    'gm3_longitude_text' => array(
      'label' => t('Geo: Point that only show longitude'),
      'description' => t('Longitude entered into a text box'),
      'field types' => array(
        'gm3_point'
      )
    ),
  );
}

/**
 * Implementation of the hook_field_formatter_info
 * 
 * To add the definitions of the text formatters for the 
 * field.
 */
function gm3_field_tweaks_field_formatter_info(){
  return array(
    'gm3_short' => array(
      'label' => t('Geo field short text format.'),
      'field types' => array(
        'gm3_point',
      )
    ),
    'gm3_latitude' => array(
      'label' => t('Geo field latitude.'),
      'field types' => array(
        'gm3_point',
      )
    ),
    'gm3_longitude' => array(
      'label' => t('Geo field longitude.'),
      'field types' => array(
        'gm3_point',
      )
    ),
  );
}


/**
 * Implement the function to be called by the definitiosn added
 * in the hook_theme implementation of this module.
 *
 * Add the markup for the gm3_short_text formatter
 */
function theme_gm3_short_text($variables){
  return array(
    '#markup' => t('%longitude, %latitude', array(
      '%longitude' => $variables['data']['longitude'],
      '%latitude' => $variables['data']['latitude']
    ))
  );
}

/**
 * Implement the function to be called by the definitiosn added
 * in the hook_theme implementation of this module.
 *
 * Add the markup for the gm3_latitude_text formatter
 */
function theme_gm3_latitude_text($variables){
  return array(
    '#markup' => t('%latitude', array(
      '%latitude' => $variables['data']['latitude']
    ))
  );
}

/**
 * Implement the function to be called by the definitiosn added
 * in the hook_theme implementation of this module.
 *
 * Add the markup for the gm3_longitude_text formatter
 */
function theme_gm3_longitude_text($variables){
  return array(
    '#markup' => t('%longitude', array(
      '%longitude' => $variables['data']['longitude'],
    ))
  );
}


/**
 * Implement the function to be called by the definitiosn added
 * in the hook_theme implementation of this module.
 *
 * Add the markup for the short_text formatter
 */
function theme_short_text($variables){
  return theme('gm3_short_text', $variables);
}

/**
 * Implement the function to be called by the definitiosn added
 * in the hook_theme implementation of this module.
 *
 * Add the markup for the latitude_text formatter
 */
function theme_latitude_text($variables){
  return theme('gm3_latitude_text', $variables);
}

/**
 * Implement the function to be called by the definitiosn added
 * in the hook_theme implementation of this module.
 *
 * Add the markup for the longitude_text formatter
 */
function theme_longitude_text($variables){
  return theme('gm3_longitude_text', $variables);
}

/**
 * Implementation of the hook_field_formatter_info.
 *
 * To glue all the previous hooks in this file together
 */
function gm3_field_tweaks_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display){

  switch($display['type']){
    case 'gm3_short':
    case 'gm3_latitude':
    case 'gm3_longitude':
      $elements = array();
      foreach($items as $item){
        $elements[] = theme($display['type'] . '_text', array(
          'data' => $item
        ));
      }
      return $elements;
      break;
  }
}
